-- Legacy DAO tables (separate from JPA-managed tables)
-- These use abbreviated column names to demonstrate SQL extraction patterns

CREATE TABLE IF NOT EXISTS T_LEGACY_CUSTOMER (
    CUST_ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUST_FIRST_NM   VARCHAR(100),
    CUST_LAST_NM    VARCHAR(100),
    CUST_EMAIL       VARCHAR(200),
    CUST_PHONE       VARCHAR(20),
    CUST_STS_CDE     CHAR(1),
    CUST_EMPL_TP_CDE VARCHAR(20),
    CUST_CRDT_SCR    INT,
    CUST_ANN_INC     DECIMAL(15,2),
    CUST_YRS_EMPL    INT
);

CREATE TABLE IF NOT EXISTS T_LEGACY_ACCOUNT (
    ACCT_ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACCT_CUST_ID    BIGINT,
    ACCT_TP_CDE     VARCHAR(20),
    ACCT_BAL        DECIMAL(15,2),
    ACCT_STS_CDE    CHAR(1),
    ACCT_OPEN_DT    DATE,
    CONSTRAINT FK_ACCT_CUST FOREIGN KEY (ACCT_CUST_ID) REFERENCES T_LEGACY_CUSTOMER(CUST_ID)
);

CREATE TABLE IF NOT EXISTS T_LEGACY_TRANSACTION (
    TXN_ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    TXN_ACCT_ID     BIGINT,
    TXN_TP_CDE      VARCHAR(20),
    TXN_AMT         DECIMAL(15,2),
    TXN_MERCH_CAT   VARCHAR(30),
    TXN_MERCH_DIST  DECIMAL(10,2),
    TXN_VERIFIED     BOOLEAN,
    TXN_INTL         BOOLEAN,
    TXN_HOUR         INT,
    TXN_DT           TIMESTAMP,
    TXN_DESC         VARCHAR(500),
    CONSTRAINT FK_TXN_ACCT FOREIGN KEY (TXN_ACCT_ID) REFERENCES T_LEGACY_ACCOUNT(ACCT_ID)
);
